"""Build the editable, original Dad/Coppola driver in Blender and export its rig.

Run: blender --background --python scripts/build-dad-driver.py
The supplied photograph is visual reference only: never read, copied or embedded.
Source coordinates X left, -Y forward, Z up; GLB export converts to Y up / Z forward.
"""
import bpy, math, random, json, struct
from pathlib import Path
from mathutils import Vector, Matrix
from math import sin, cos, pi, sqrt

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'public' / 'assets'
SOURCE = ROOT / 'asset-source'
DOCS = ROOT / 'docs'
for directory in (ASSETS, SOURCE, DOCS): directory.mkdir(parents=True, exist_ok=True)
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)
for datablocks in (bpy.data.meshes, bpy.data.curves, bpy.data.armatures, bpy.data.materials, bpy.data.actions):
    for item in list(datablocks):
        if item.users == 0: datablocks.remove(item)
random.seed(442)
scene = bpy.context.scene
scene.unit_settings.system = 'METRIC'
scene.unit_settings.scale_length = 1
scene.render.fps = 30
collection = bpy.data.collections.new('DAD DRIVER | editable skinned character')
scene.collection.children.link(collection)
objects = []

def move_collection(obj):
    for c in list(obj.users_collection): c.objects.unlink(obj)
    collection.objects.link(obj)

def material(name, color, roughness=.65, metallic=0):
    m=bpy.data.materials.new(name); m.diffuse_color=(*color,1); m.use_nodes=True
    bsdf=m.node_tree.nodes.get('Principled BSDF')
    bsdf.inputs['Base Color'].default_value=(*color,1)
    bsdf.inputs['Roughness'].default_value=roughness
    bsdf.inputs['Metallic'].default_value=metallic
    return m

skin=material('Warm natural skin',(.44,.235,.155),.62)
skin.node_tree.nodes.get('Principled BSDF').inputs['Subsurface Weight'].default_value=.10
skin.node_tree.nodes.get('Principled BSDF').inputs['Subsurface Radius'].default_value=(1,.45,.25)
crease=material('Soft warm creases',(.31,.148,.101),.8)
lip=material('Natural muted lip',(.46,.21,.178),.63)
hair=material('Salt and pepper side hair',(.155,.143,.133),.92)
silver=material('Mustache silver',(.66,.65,.59),.85)
white=material('Mustache white highlights',(.86,.84,.77),.88)
darkhair=material('Individual dark hairs',(.07,.061,.052),.94)
eyeWhite=material('Warm eye whites',(.35,.31,.27),.70)
iris=material('Brown irises',(.03,.018,.01),.65)
pupil=material('Pupils',(.003,.003,.002),.8)
wire=material('Warm graphite wire spectacles',(.14,.116,.089),.34,.65)
lens=material('Lightly tinted spectacle lenses',(.075,.040,.028),.25,.02)
lens.diffuse_color=(.075,.040,.028,.62)
bs=lens.node_tree.nodes.get('Principled BSDF'); bs.inputs['Alpha'].default_value=.62
bs.inputs['Transmission Weight'].default_value=0
bs.inputs['IOR'].default_value=1.45
lens.surface_render_method='DITHERED'
shirt=material('Light blue checked cotton',(.40,.62,.75),.83)
tee=material('Charcoal V neck knit',(.065,.071,.08),.95)
trousers=material('Dark charcoal trousers',(.047,.055,.066),.93)
leather=material('Soft black leather shoes',(.026,.025,.023),.46)
sole=material('Rubber soles',(.017,.019,.018),.96)
cap=material('Charcoal herringbone Coppola tweed',(.095,.10,.105),.91)
stitch=material('Quiet blue cotton stitching',(.235,.405,.50),.88)
capstitch=material('Cap seam thread',(.10,.103,.105),.94)
button=material('Pearl blue shirt buttons',(.34,.48,.55),.4)

def fabric(m, kind, size=512):
    import numpy as np
    rng=np.random.default_rng(1968 if kind=='checks' else 1948)
    y,x=np.mgrid[:size,:size]
    weave=(np.sin(x*pi)*.004 + np.sin(y*pi)*.004)
    noise=rng.normal(0,.018,(size,size))
    if kind=='checks':
        base=np.array([.37,.58,.75])
        period=size/8
        dx=np.minimum(x%period, period-x%period)
        dy=np.minimum(y%period, period-y%period)
        line=np.maximum(np.clip((1.5-dx)/1.5,0,1),np.clip((1.5-dy)/1.5,0,1))
        fine=np.maximum(np.clip((.7-abs(dx-4))/.7,0,1),np.clip((.7-abs(dy-4))/.7,0,1))
        rgb=base[None,None,:]*(1-.25*line[:,:,None]-.12*fine[:,:,None])+noise[:,:,None]*.36
    elif kind=='tweed':
        base=np.array([.09,.098,.105])
        direction=np.where((x//24)%2==0,1,-1)
        chevron=np.sin((x+direction*y)*pi/5)
        rgb=base[None,None,:]+(.022*chevron+noise*.8)[:,:,None]
    else:
        base=np.array([.09,.097,.105])
        rgb=base[None,None,:]+noise[:,:,None]*.36
    rgba=np.ones((size,size,4),dtype=np.float32)
    rgba[:,:,:3]=np.clip(rgb,0,1)
    image=bpy.data.images.new('Original baked '+kind, width=size,height=size)
    image.pixels.foreach_set(rgba.ravel()); image.pack()
    image['provenance']='Original procedural cotton/tweed pixels generated by build-dad-driver.py; no photographic pixels.'
    nodes=m.node_tree.nodes; texture=nodes.new('ShaderNodeTexImage'); texture.image=image
    texture.interpolation='Linear'; texture.extension='REPEAT'
    m.node_tree.links.new(texture.outputs['Color'],nodes.get('Principled BSDF').inputs['Base Color'])
    bump=nodes.new('ShaderNodeBump'); bump.inputs['Strength'].default_value=.13; bump.inputs['Distance'].default_value=.00025
    m.node_tree.links.new(texture.outputs['Color'],bump.inputs['Height'])
    m.node_tree.links.new(bump.outputs['Normal'],nodes.get('Principled BSDF').inputs['Normal'])
fabric(shirt,'checks'); fabric(cap,'tweed'); fabric(tee,'knit')

def weights(obj, bone=None, field=None):
    if field:
        for v in obj.data.vertices:
            for name,weight in field(v.co).items():
                if weight <= 0: continue
                group=obj.vertex_groups.get(name) or obj.vertex_groups.new(name=name)
                group.add([v.index],weight,'REPLACE')
    else:
        group=obj.vertex_groups.new(name=bone or 'torso'); group.add(list(range(len(obj.data.vertices))),1,'REPLACE')
    objects.append(obj); move_collection(obj)
    return obj

def mesh(name, vertices, faces, mat, bone=None, field=None, uvs=None):
    data=bpy.data.meshes.new(name); data.from_pydata(vertices,[],faces); data.update()
    obj=bpy.data.objects.new(name,data); collection.objects.link(obj); data.materials.append(mat)
    for poly in data.polygons: poly.use_smooth=True
    uv=data.uv_layers.new(name='UVMap')
    for poly in data.polygons:
        for li in poly.loop_indices:
            vi=data.loops[li].vertex_index
            p=data.vertices[vi].co
            uv.data[li].uv=uvs[vi] if uvs else (p.x*5,p.z*5)
    return weights(obj,bone,field)

def ellipsoid(name, location, scale, mat, bone='head', segments=32, rings=20, rotation=(0,0,0)):
    bpy.ops.mesh.primitive_uv_sphere_add(segments=segments,ring_count=rings,location=location)
    obj=bpy.context.object; obj.name=name; obj.scale=scale; obj.rotation_euler=rotation
    bpy.ops.object.transform_apply(location=True,rotation=True,scale=True)
    obj.data.materials.append(mat)
    for poly in obj.data.polygons: poly.use_smooth=True
    return weights(obj,bone)

def curve(name, points, radius, mat, bone='head', sides=4):
    data=bpy.data.curves.new(name,'CURVE'); data.dimensions='3D'; data.resolution_u=2
    data.bevel_depth=radius; data.bevel_resolution=1 if sides<=4 else 2
    poly=data.splines.new('POLY'); poly.points.add(len(points)-1)
    for q,p in zip(poly.points,points): q.co=(*p,1)
    obj=bpy.data.objects.new(name,data); collection.objects.link(obj); data.materials.append(mat)
    bpy.context.view_layer.objects.active=obj; obj.select_set(True)
    bpy.ops.object.convert(target='MESH'); obj=bpy.context.object; obj.select_set(False)
    for face in obj.data.polygons: face.use_smooth=True
    return weights(obj,bone)

def profile(z, rows):
    for index,(a,b) in enumerate(zip(rows,rows[1:])):
        if a[0] <= z <= b[0]:
            t=(z-a[0])/(b[0]-a[0]);span=b[0]-a[0]
            previous=rows[max(0,index-1)];following=rows[min(len(rows)-1,index+2)]
            values=[]
            for i in range(1,len(a)):
                ma=(b[i]-previous[i])/(b[0]-previous[0])*span
                mb=(following[i]-a[i])/(following[0]-a[0])*span
                values.append((2*t**3-3*t*t+1)*a[i]+(t**3-2*t*t+t)*ma+(-2*t**3+3*t*t)*b[i]+(t**3-t*t)*mb)
            return tuple(values)
    return rows[0][1:] if z<rows[0][0] else rows[-1][1:]

def torso_weights(p):
    t=max(0,min(1,(p.z-1.015)/.15))
    return {'hips':1-t,'torso':t}

# Continuous rounded torso, with an actual V opening at the neckline.
torso_profile=[(.975,.175,.13,.12),(1.04,.198,.164,.135),(1.16,.241,.201,.149),(1.29,.239,.165,.140),(1.37,.245,.126,.125),(1.43,.10,.083,.082)]
vertices=[];faces=[];uvs=[]; N=64; R=28
for j in range(R+1):
    t=j/R
    for i in range(N+1):
        a=2*pi*i/N; front=max(0,cos(a))
        top=1.428-.120*front**16
        z=.985+(top-.985)*t
        width,df,db=profile(z,torso_profile)
        vertices.append((sin(a)*width,-cos(a)*(df if cos(a)>0 else db),z))
        uvs.append((i/N*3,t*2))
for j in range(R):
    for i in range(N):
        a=j*(N+1)+i; faces.append((a,a+1,a+N+2,a+N+1))
mesh('Charcoal anatomical V-neck torso',vertices,faces,tee,field=torso_weights,uvs=uvs)
# One continuous chest/neck surface avoids the visible ring made by intersecting
# an ellipsoid with a narrower chest. The upper neck overlaps the jaw internally.
bare_rows=[(1.235,.217,.170,.13),(1.30,.231,.151,.134),(1.37,.231,.122,.122),(1.40,.195,.102,.106),(1.435,.110,.084,.087),(1.46,.078,.070,.073),(1.49,.069,.063,.069),(1.53,.063,.061,.064)]
verts=[];faces=[];N=48;R=30
for j in range(R+1):
    z=1.235+.295*j/R;rx,df,db=profile(z,bare_rows)
    for i in range(N+1):
        a=2*pi*i/N;verts.append((sin(a)*rx,-cos(a)*(df if cos(a)>0 else db),z))
for j in range(R):
    for i in range(N):
        a=j*(N+1)+i;faces.append((a,a+1,a+N+2,a+N+1))
mesh('Continuous upper chest and neck foundation',verts,faces,skin,'torso')
for side in (-1,1):
    # A continuous tailored shoulder surface bridges collar to sleeve; it is
    # a thin garment panel rather than a separate rounded shoulder-pad volume.
    shoulder=[]; shoulder_faces=[]; shoulder_uv=[]; U=12;V=14
    for j in range(U+1):
        u=j/U;x=side*(.065+.218*u);width=.078+.025*sin(pi*u)
        for k in range(V+1):
            v=-1+2*k/V;y=v*width
            z=1.444-.036*u-.026*v*v+.004*sin(pi*u)
            shoulder.append((x,y,z));shoulder_uv.append((x*4.4,y*4.4))
    for j in range(U):
        for k in range(V):
            a=j*(V+1)+k;q=(a,a+V+1,a+V+2,a+1);shoulder_faces.append(q if side>0 else q[::-1])
    mesh('Continuous cotton shoulder '+str(side),shoulder,shoulder_faces,shirt,'torso',uvs=shoulder_uv)
    # The shoulder turns continuously down into the breast and upper sleeve.
    # This fills the seam between the tapering torso rings and shoulder cap.
    for facing in (-1,1):
        verts=[];faces=[];uvs=[];U=18;V=9
        for j in range(U+1):
            u=j/U;x=side*(.10+.183*u)
            topy=facing*(.078+.025*sin(pi*u));topz=1.444-.036*u-.026+.004*sin(pi*u)
            bottomz=1.345
            width,df,db=profile(bottomz,torso_profile)
            body_y=sqrt(max(0,1-(abs(x)/(width+.009))**2))*((df if facing<0 else db)+.009)
            sleeve_y=sqrt(max(0,1-((abs(x)-.261)/.073)**2))*.079
            bottomy=facing*max(body_y,sleeve_y)
            for k in range(V+1):
                t=k/V;smooth=t*t*(3-2*t)
                y=topy+(bottomy-topy)*smooth;z=topz+(bottomz-topz)*t
                verts.append((x,y,z));uvs.append((x*4.4,z*4.4))
        for j in range(U):
            for k in range(V):
                a=j*(V+1)+k;quad=(a,a+1,a+V+2,a+V+1);faces.append(quad if side*facing<0 else quad[::-1])
        mesh('Continuous shoulder turn '+str((side,facing)),verts,faces,shirt,'torso',uvs=uvs)
    vertices=[];faces=[];uvs=[]; N=40;R=28
    for j in range(R+1):
        t=j/R; z=1.003+.421*t
        width,df,db=profile(z,torso_profile)
        opening=.245+.22*t**2
        for i in range(N+1):
            a=side*(opening+(pi-opening)*i/N)
            height=z-.011*max(0,cos(a))*t**9
            vertices.append((sin(a)*(width+.007),-cos(a)*((df if cos(a)>0 else db)+.007),height))
            uvs.append((a/pi*2.8,z*4.4))
    for j in range(R):
        for i in range(N):
            a=j*(N+1)+i; face=(a,a+1,a+N+2,a+N+1);faces.append(face if side>0 else face[::-1])
    mesh(('Left' if side>0 else 'Right')+' open checked shirt panel',vertices,faces,shirt,field=torso_weights,uvs=uvs)
    seam=[]
    for j in range(31):
        t=j/30;z=1.006+.405*t;w,df,db=profile(z,torso_profile);a=side*(.245+.22*t*t)
        seam.append((sin(a)*(w+.009),-cos(a)*(df+.009),z))
    curve('Shirt front folded placket '+str(side),seam,.0048,shirt,'torso')
    # Collar falls naturally outwards over the chest instead of a stiff neck ring.
    collar=[(side*.055,-.079,1.465),(side*.112,-.081,1.411),(side*.129,-.139,1.355),(side*.081,-.157,1.374),(side*.058,-.113,1.422)]
    obj=mesh('Open cotton collar '+str(side),collar,[tuple(range(5))],shirt,'torso')
    solid=obj.modifiers.new('Tailored fabric thickness','SOLIDIFY');solid.thickness=.0025
    bevel=obj.modifiers.new('Soft collar edges','BEVEL');bevel.width=.0025;bevel.segments=2
    if side>0:
        for z in (1.10,1.19,1.28):
            w,df,db=profile(z,torso_profile);a=.245+.22*((z-1.003)/.421)**2
            ellipsoid('Small shirt button',(sin(a)*(w+.014),-cos(a)*(df+.014),z),(.0033,.002,.0033),button,'torso',12,8)
    # One subtle patch pocket, following the round chest.
    if side<0:
        pocket=[(-.105,-.165,1.265),(-.194,-.124,1.265),(-.187,-.139,1.167),(-.102,-.182,1.167)]
        mesh('Left breast pocket',pocket,[(0,1,2,3)],shirt,'torso')
        curve('Pocket upper stitching',[pocket[0],pocket[1]],.0012,stitch,'torso')

# Smooth sleeves and trousers span joints, with blended armature weights.
for side,label in ((1,'left'),(-1,'right')):
    def arm_weight(p,label=label):
        t=max(0,min(1,(p.z-1.066)/.085))
        return {label+'_arm':t,label+'_forearm':1-t}
    rows=[(.843,.050,.054),(.88,.054,.059),(1.05,.063,.070),(1.12,.067,.071),(1.26,.071,.076),(1.375,.073,.077),(1.404,.055,.061)]
    verts=[]; faces=[];uvs=[];N=28;R=30
    for j in range(R+1):
        z=.841+(.563)*j/R;rx,ry=profile(z,rows)
        cx=side*(.288-(z-.84)/.563*.032)
        for i in range(N+1):
            a=2*pi*i/N;wrinkle=1+.018*sin(a*3+z*62)*sin(j/R*pi)
            verts.append((cx+sin(a)*rx*wrinkle,-cos(a)*ry*wrinkle,z));uvs.append((i/N*2.2,z*4.6))
    for j in range(R):
        for i in range(N):
            a=j*(N+1)+i;faces.append((a,a+1,a+N+2,a+N+1))
    faces.append(tuple(range(N,-1,-1)))
    faces.append(tuple(R*(N+1)+i for i in range(N+1)))
    mesh(label+' continuous checked sleeve',verts,faces,shirt,field=arm_weight,uvs=uvs)
    ellipsoid(label+' cuff',(side*.288,0,.864),(.056,.061,.030),shirt,label+'_forearm',24,12)
    ellipsoid(label+' palm',(side*.291,-.003,.804),(.043,.027,.060),skin,label+'_hand',28,18)
    for f in range(4):
        x=side*.291+(f-1.5)*.018
        length=(.078,.090,.087,.069)[f]
        points=[(x,-.006,.794),(x,-.012,.766),(x,-.030,.794-length+.005),(x,-.047,.794-length+.017)]
        curve(label+' finger '+str(f),points,.009 if f<3 else .008,skin,label+'_hand',6)
        ellipsoid(label+' fingertip '+str(f),points[-1],(.009,.010,.010),skin,label+'_hand',12,8)
        ellipsoid(label+' fingernail '+str(f),(points[-1][0],points[-1][1]-.008,points[-1][2]+.004),(.005,.0013,.007),lip,label+'_hand',12,8)
    thumb=[(side*.266,-.01,.827),(side*.245,-.03,.803),(side*.239,-.04,.782)]
    curve(label+' curved thumb',thumb,.012,skin,label+'_hand',6)
    ellipsoid(label+' thumb tip',thumb[-1],(.012,.011,.014),skin,label+'_hand',12,10)

    def leg_weight(p,label=label):
        t=max(0,min(1,(p.z-.475)/.085))
        hip=max(0,min(.50,(p.z-.88)*5))
        return {label+'_thigh':t*(1-hip),label+'_shin':(1-t)*(1-hip),'hips':hip}
    rows=[(.07,.067,.075),(.15,.073,.080),(.39,.076,.084),(.52,.083,.090),(.69,.089,.106),(.88,.093,.113),(1.02,.091,.12)]
    verts=[];faces=[];uvs=[];N=28;R=36
    for j in range(R+1):
        z=.076+.929*j/R;rx,ry=profile(z,rows)
        for i in range(N+1):
            a=2*pi*i/N
            fold=.003*sin(z*81+a*2)*math.exp(-((z-.52)/.11)**2)
            verts.append((side*.104+sin(a)*(rx+fold),-cos(a)*(ry+fold),z));uvs.append((i/N,z*3))
    for j in range(R):
        for i in range(N):
            a=j*(N+1)+i;faces.append((a,a+1,a+N+2,a+N+1))
    mesh(label+' tailored trouser leg',verts,faces,trousers,field=leg_weight,uvs=uvs)
    ellipsoid(label+' leather shoe',(side*.104,-.053,.062),(.086,.145,.058),leather,label+'_foot',36,18)
    ellipsoid(label+' low rubber sole',(side*.104,-.054,.018),(.088,.146,.016),sole,label+'_foot',36,12)
    curve(label+' shoe vamp seam',[(side*.104+cos(t)*.071,-.079+sin(t)*.062,.095) for t in [pi+i*pi/20 for i in range(21)]],.0016,sole,label+'_foot')
ellipsoid('Trouser seat',(0,.012,.973),(.182,.124,.102),trousers,'hips',40,20)

# Anatomical head: profile rings with cheek pads, eye sockets and brow ridge.
head_rows=[(1.502,.040,.047,.057),(1.516,.079,.077,.073),(1.541,.108,.089,.086),(1.573,.119,.093,.099),(1.613,.128,.083,.108),(1.650,.119,.082,.111),(1.69,.111,.090,.105),(1.735,.093,.091,.089),(1.772,.042,.046,.043),(1.780,.002,.003,.003)]
verts=[];faces=[];uvs=[];N=80;R=52
for j in range(R+1):
    z=1.502+.278*j/R;rx,front,back=profile(z,head_rows)
    for i in range(N+1):
        a=2*pi*i/N;x=sin(a)*rx;y=-cos(a)*(front if cos(a)>0 else back)
        face=max(0,cos(a))**3
        cheeks=.012*math.exp(-((abs(x)-.079)/.038)**2-((z-1.598)/.036)**2)
        eye_socket=.006*math.exp(-((abs(x)-.052)/.029)**2-((z-1.648)/.014)**2)
        brow=.008*math.exp(-((abs(x)-.052)/.043)**2-((z-1.673)/.014)**2)
        y-=face*(cheeks+brow-eye_socket)
        verts.append((x,y,z));uvs.append((i/N,j/R))
for j in range(R):
    for i in range(N):
        a=j*(N+1)+i;faces.append((a,a+1,a+N+2,a+N+1))
mesh('Sculpted rounded face and cranium',verts,faces,skin,'head',uvs=uvs)
for side in (-1,1):
    hairverts=[];hairfaces=[];U=24;V=12
    for j in range(V+1):
        for i in range(U+1):
            a=side*(1.12+(pi-1.12)*i/U)
            low=1.625+.035*max(0,cos(a));z=low+(1.751-low)*j/V
            rx,df,db=profile(z,head_rows)
            hairverts.append((sin(a)*(rx+.0015),-cos(a)*((df if cos(a)>0 else db)+.0015),z))
    for j in range(V):
        for i in range(U):
            a=j*(U+1)+i;q=(a,a+1,a+U+2,a+U+1);hairfaces.append(q if side>0 else q[::-1])
    mesh('Close cropped salt pepper temple '+str(side),hairverts,hairfaces,hair,'head')
for side in (-1,1):
    ellipsoid('Ear pinna '+str(side),(side*.126,.008,1.627),(.020,.014,.033),skin,'head',24,16)
    ellipsoid('Ear inner fold '+str(side),(side*.132,-.006,1.627),(.010,.004,.019),lip,'head',18,12)
    ellipsoid('Ear tragus '+str(side),(side*.121,-.010,1.621),(.008,.006,.012),skin,'head',16,12)
ellipsoid('Defined broad nose bridge',(0,-.094,1.647),(.019,.021,.044),skin,'head',32,22)
ellipsoid('Prominent rounded nose tip',(0,-.121,1.621),(.023,.020,.017),skin,'head',36,22)
for side in (-1,1):
    ellipsoid('Nose wing '+str(side),(side*.024,-.110,1.611),(.012,.016,.014),skin,'head',24,16)
    ellipsoid('Nostril shadow '+str(side),(side*.017,-.119,1.603),(.006,.003,.0035),crease,'head',18,10)
ellipsoid('Subtle lower lip',(0,-.100,1.570),(.032,.010,.0085),lip,'head',32,14)
curve('Quiet mouth separation',[(-.037,-.104,1.580),(-.018,-.109,1.578),(0,-.111,1.578),(.021,-.108,1.578),(.039,-.100,1.579)],.0017,crease)
for side in (-1,1):
    ellipsoid('Eye white '+str(side),(side*.052,-.084,1.652),(.018,.008,.007),eyeWhite,'head',28,16)
    ellipsoid('Brown iris '+str(side),(side*.052,-.092,1.652),(.006,.0018,.006),iris,'head',24,14)
    ellipsoid('Pupil '+str(side),(side*.052,-.094,1.652),(.0030,.001,.0035),pupil,'head',20,12)
    curve('Upper eyelid '+str(side),[(side*.052+cos(t)*.019,-.092,1.650+sin(t)*.009) for t in [i*pi/20 for i in range(21)]],.0018,skin)
    curve('Lower eyelid '+str(side),[(side*.052+cos(t)*.018,-.090,1.653+sin(t)*.007) for t in [pi+i*pi/20 for i in range(21)]],.0013,skin)
    # Brow strands are independent, irregular salt-and-pepper hairs.
    for n in range(25):
        x=side*(.025+n/24*.065);z=1.678+.006*sin(n/24*pi)
        curve('Brow hair',[(x,-.096,z),(x+side*.003,-.097,z+.004),(x+side*.006,-.091,z+.005)],.00075,darkhair if n%6 else hair)
    # Receding side hair lies against the skull rather than a helmet.
    for n in range(74):
        a=side*(.91+random.random()*1.67);z=1.659+random.random()*.090
        rx,df,db=profile(z,head_rows)
        p=(sin(a)*(rx+.002),-cos(a)*(df if cos(a)>0 else db)-.001,z)
        z2=min(1.764,z+.010+random.random()*.012);rx2,df2,db2=profile(z2,head_rows)
        p2=(sin(a+.035*side)*(rx2+.002),-cos(a+.035*side)*(df2 if cos(a+.035*side)>0 else db2)-.001,z2)
        curve('Combed salt pepper hair',[p,p2],.00072,silver if n%3==0 else darkhair)

# Thick familiar white mustache, with curled/drooping ends and separate strands.
for side in (-1,1):
    ellipsoid('Mustache soft lobe '+str(side),(side*.028,-.107,1.591),(.035,.006,.011),silver,'head',32,16,rotation=(0,side*.19,0))
    ellipsoid('Mustache drooping end '+str(side),(side*.059,-.098,1.580),(.009,.006,.010),silver,'head',20,14,rotation=(0,side*.35,0))
for n in range(210):
    x=(random.random()*2-1)*.064;side=1 if x>=0 else -1
    rootz=1.607-.020*(abs(x)/.064)**1.4+random.random()*.002
    y=-.118+.017*(abs(x)/.064)**1.4
    length=.017+random.random()*.011
    curve('Silver mustache strand',[(x,y,rootz),(x+side*.002,y-.003,rootz-length*.35),(x+side*.004,y-.001,rootz-length*.77),(x+side*.006,y+.003,rootz-length)],.00058,white if n%4 else silver)

# Rounded thin-wire tinted glasses, bridged and fitted over the ears.
for side in (-1,1):
    cx=side*.055
    points=[(cx+cos(t)*.047,-.128+abs(sin(t))*.002,1.647+sin(t)*.032) for t in [i*2*pi/64 for i in range(65)]]
    curve('Rounded wire lens rim '+str(side),points,.00155,wire)
    verts=[(cx,-.128,1.647)];uv=[(.5,.5)]
    for i in range(65):
        a=2*pi*i/64;verts.append((cx+cos(a)*.0455,-.127,1.647+sin(a)*.0305));uv.append((.5+cos(a)*.5,.5+sin(a)*.5))
    mesh('Tinted clear lens '+str(side),verts,[(0,i+1,i+2) for i in range(64)],lens,'head',uvs=uv)
    curve('Wire temple '+str(side),[(side*.102,-.125,1.659),(side*.117,-.079,1.661),(side*.127,-.008,1.655),(side*.125,.013,1.641)],.00175,wire)
    ellipsoid('Nose pad '+str(side),(side*.014,-.114,1.644),(.003,.004,.005),button,'head',12,8)
curve('Arched spectacle bridge',[(-.009,-.128,1.657),(-.005,-.133,1.663),(0,-.135,1.665),(.005,-.133,1.663),(.009,-.128,1.657)],.00155,wire)

# Italian Coppola: a low continuous sloping crown and short crescent brim.
verts=[];faces=[];uv=[];N=48;R=14
for j in range(R+1):
    r=.003+.997*j/R
    for i in range(N+1):
        a=2*pi*i/N;x=.128*r*sin(a);y=.012-.137*r*cos(a)
        z=1.745+.055*(1-r*r)**.60+y*.115-.004*max(0,-y/.13)
        verts.append((x,y,z));uv.append((.5+x*5,.5+y*5))
for j in range(R):
    for i in range(N):
        a=j*(N+1)+i;faces.append((a,a+1,a+N+2,a+N+1))
crown=mesh('Coppola low sloped tweed crown',verts,faces,cap,'head',uvs=uv)
solid=crown.modifiers.new('Wool fabric thickness','SOLIDIFY');solid.thickness=.003
rim=[(.119*sin(a),.012-.127*cos(a),1.744+(.012-.127*cos(a))*.115) for a in [i*2*pi/96 for i in range(97)]]
curve('Coppola fitted narrow band',rim,.005,cap)
verts=[];faces=[];uv=[];N=48;R=6
for j in range(R+1):
    t=j/R
    for i in range(N+1):
        u=-1+2*i/N;arc=sqrt(max(0,1-u*u))
        x=.105*u;y=-.078-arc*(.040+.031*t);z=1.735-.010*t+.003*u*u
        verts.append((x,y,z));uv.append((x*6,y*6))
for j in range(R):
    for i in range(N):
        a=j*(N+1)+i;faces.append((a,a+1,a+N+2,a+N+1))
brim=mesh('Coppola short curved stiff brim',verts,faces,cap,'head',uvs=uv)
solid=brim.modifiers.new('Bound brim thickness','SOLIDIFY');solid.thickness=.004
curve('Coppola subtle center seam',[(0,.012-.136*cos(a),1.745+.055*abs(sin(a))**1.2+(.012-.136*cos(a))*.115-.004*max(0,-(.012-.136*cos(a))/.13)+.002) for a in [i*pi/64 for i in range(65)]],.00075,capstitch)
# Fit the completed cap to the tapered upper skull without changing its low
# sloping silhouette, short brim, head weights, or any animation transforms.
for obj in objects:
    if obj.data.materials[0] not in (cap,capstitch):continue
    for vertex in obj.data.vertices:
        vertex.co.x*=.965
        vertex.co.y=.006+(vertex.co.y-.006)*.97
        vertex.co.z-=.020

# Voxel-unify the sculpted head/nose/ears so the portrait has continuous flesh
# rather than visible seams between individual anatomical construction forms.
face_objects=[obj for obj in objects if obj.data.materials[0]==skin and obj.vertex_groups.get('head')]
bpy.ops.object.select_all(action='DESELECT')
for obj in face_objects:obj.select_set(True)
bpy.context.view_layer.objects.active=face_objects[0]
bpy.ops.object.join();face=bpy.context.object;face.name='Unified sculpted dad head'
bpy.ops.object.mode_set(mode='EDIT');bpy.ops.mesh.select_all(action='SELECT')
bpy.ops.mesh.remove_doubles(threshold=.00001);bpy.ops.mesh.fill_holes(sides=96)
bpy.ops.mesh.normals_make_consistent(inside=False);bpy.ops.object.mode_set(mode='OBJECT')
remesh=face.modifiers.new('Anatomical voxel union','REMESH');remesh.mode='VOXEL';remesh.voxel_size=.0024;remesh.use_smooth_shade=True
bpy.ops.object.modifier_apply(modifier=remesh.name)
smooth=face.modifiers.new('Sculpt surface polish','SMOOTH');smooth.factor=.55;smooth.iterations=4
bpy.ops.object.modifier_apply(modifier=smooth.name)
decimate=face.modifiers.new('Portrait topology optimization','DECIMATE');decimate.ratio=.105
bpy.ops.object.modifier_apply(modifier=decimate.name)
# Preserve a small clearance inside the lowered cap. Only the hidden upper
# cranium changes; the brow, facial likeness and head animation bind stay fixed.
for vertex in face.data.vertices:
    t=max(0,min(1,(vertex.co.z-1.710)/.070))
    vertex.co.z-=.014*t*t
face.vertex_groups.clear();group=face.vertex_groups.new(name='head');group.add(list(range(len(face.data.vertices))),1,'REPLACE')
assert len(face.data.vertices)>3500, 'Unified anatomical head must retain its full cranium'
face.data.validate();face.data.update()
objects=[o for o in collection.objects if o.type=='MESH']

# Apply small cloth modifiers before skinning and material-batch the character.
for obj in list(objects):
    bpy.context.view_layer.objects.active=obj
    for mod in list(obj.modifiers): bpy.ops.object.modifier_apply(modifier=mod.name)

armature=bpy.data.armatures.new('Dad driver skeleton')
rig=bpy.data.objects.new('DadDriverRig',armature);collection.objects.link(rig)
bpy.context.view_layer.objects.active=rig;rig.select_set(True)
bpy.ops.object.mode_set(mode='EDIT')
specs={
 'hips':((0,0,.94),(0,0,1.06),None),
 'torso':((0,0,1.06),(0,0,1.485),'hips'),
 'head':((0,0,1.485),(0,0,1.78),'torso'),
}
for side,label in ((1,'left'),(-1,'right')):
    specs.update({
      label+'_arm':((side*.265,0,1.392),(side*.28,0,1.107),'torso'),
      label+'_forearm':((side*.28,0,1.107),(side*.288,0,.842),label+'_arm'),
      label+'_hand':((side*.288,0,.842),(side*.293,-.010,.743),label+'_forearm'),
      label+'_thigh':((side*.104,0,.935),(side*.104,0,.513),'hips'),
      label+'_shin':((side*.104,0,.513),(side*.104,0,.088),label+'_thigh'),
      label+'_foot':((side*.104,0,.088),(side*.104,-.12,.060),label+'_shin'),
    })
for name,(head,tail,parent) in specs.items():
    bone=armature.edit_bones.new(name);bone.head=head;bone.tail=tail;bone.roll=0
    if parent:bone.parent=armature.edit_bones[parent]
bpy.ops.object.mode_set(mode='OBJECT');rig.select_set(False)
rig.show_in_front=True;armature.display_type='STICK'

# Join per material: preserves named deform vertex groups and the editable rig.
batched=[]
material_batches=[(mat,[o for o in objects if o.type=='MESH' and o.data.materials and o.data.materials[0]==mat]) for mat in list(bpy.data.materials)]
for mat,batch in material_batches:
    if not batch:continue
    bpy.ops.object.select_all(action='DESELECT')
    for o in batch:o.select_set(True)
    bpy.context.view_layer.objects.active=batch[0]
    bpy.ops.object.join();obj=bpy.context.object;obj.name='Dad | '+mat.name
    obj.parent=rig
    modifier=obj.modifiers.new('Dad anatomical armature','ARMATURE');modifier.object=rig;modifier.use_vertex_groups=True
    batched.append(obj)

def reset_pose():
    for bone in rig.pose.bones:
        bone.rotation_mode='XYZ';bone.rotation_euler=(0,0,0);bone.location=(0,0,0);bone.scale=(1,1,1)

def sole_height():
    z=100
    for obj in batched:
        if not ('shoe' in obj.name.lower() or 'sole' in obj.name.lower()):continue
        for v in obj.data.vertices:
            if not v.groups:continue
            group=obj.vertex_groups[v.groups[0].group].name
            pb=rig.pose.bones[group]
            point=pb.matrix @ pb.bone.matrix_local.inverted() @ v.co
            z=min(z,point.z)
    return z

def reach_wheel(label, side):
    """Bake a two-bone downward-elbow reach to the original steering wheel."""
    upper=rig.pose.bones[label+'_arm'];lower=rig.pose.bones[label+'_forearm']
    bpy.context.view_layer.update()
    shoulder=upper.head.copy();target=Vector((side*.145,-.357,.938))
    direction=target-shoulder;distance=direction.length;direction.normalize()
    a=upper.bone.length;b=lower.bone.length
    along=(a*a-b*b+distance*distance)/(2*distance)
    bend=Vector((side*.2,0,-1));bend-=direction*direction.dot(bend);bend.normalize()
    elbow=shoulder+direction*along+bend*sqrt(max(0,a*a-along*along))
    for bone,end in ((upper,elbow),(lower,target)):
        bpy.context.view_layer.update();head=bone.head.copy()
        rotation=(bone.tail-head).rotation_difference(end-head)
        bone.matrix=Matrix.Translation(head) @ rotation.to_matrix().to_4x4() @ Matrix.Translation(-head) @ bone.matrix
    bpy.context.view_layer.update()

clips={}
for action_name,frames,kind in [('Idle',61,'idle'),('Walk',21,'walk'),('Run',16,'run'),('Airborne',31,'airborne'),('Seated',31,'seated')]:
    reset_pose()
    action=bpy.data.actions.new(action_name);rig.animation_data_create();rig.animation_data.action=action
    for frame in sorted(set(list(range(1,frames+1,2))+[frames])):
        reset_pose();phase=(frame-1)/(frames-1)*2*pi
        if kind=='idle':
            rig.pose.bones['torso'].rotation_euler.x=sin(phase)*.008
            rig.pose.bones['head'].rotation_euler.y=sin(phase)*.018
        elif kind in ('walk','run'):
            running=kind=='run';swing=sin(phase)*(.78 if running else .47)
            rig.pose.bones['torso'].rotation_euler.x=.10 if running else .025
            rig.pose.bones['torso'].rotation_euler.y=swing*.12
            for i,label in enumerate(('right','left')):
                rig.pose.bones[label+'_thigh'].rotation_euler.x=swing if i==0 else -swing
                rig.pose.bones[label+'_shin'].rotation_euler.x=max(0,sin(phase+i*pi))*(1.20 if running else .65)
                rig.pose.bones[label+'_arm'].rotation_euler.x=(-swing if i==0 else swing)*.9
                rig.pose.bones[label+'_forearm'].rotation_euler.x=-.94 if running else -.16
            bpy.context.view_layer.update()
            rig.pose.bones['hips'].location.y+=.004-sole_height()
        elif kind=='seated':
            rig.pose.bones['hips'].location.y=-.29
            rig.pose.bones['torso'].rotation_euler.x=-.10
            rig.pose.bones['head'].rotation_euler.x=.07
            for side,label in ((1,'left'),(-1,'right')):
                rig.pose.bones[label+'_thigh'].rotation_euler.x=-1.53
                rig.pose.bones[label+'_shin'].rotation_euler.x=.60
                rig.pose.bones[label+'_foot'].rotation_euler.x=.92
                reach_wheel(label,side)
                rig.pose.bones[label+'_hand'].rotation_euler.y=side*1.10
        else:
            rig.pose.bones['torso'].rotation_euler.x=.09
            for side,label in ((1,'left'),(-1,'right')):
                rig.pose.bones[label+'_arm'].rotation_euler.x=-.55
                rig.pose.bones[label+'_forearm'].rotation_euler.x=-.55
                rig.pose.bones[label+'_thigh'].rotation_euler.x=-.36 if side>0 else .14
                rig.pose.bones[label+'_shin'].rotation_euler.x=.61 if side>0 else .28
        for bone in rig.pose.bones:
            bone.keyframe_insert('rotation_euler',frame=frame,group=bone.name)
            bone.keyframe_insert('location',frame=frame,group=bone.name)
    action.use_fake_user=True
    track=rig.animation_data.nla_tracks.new();track.name=action_name
    strip=track.strips.new(action_name,1,action);track.mute=True
    clips[action_name]={'durationSeconds':(frames-1)/30,'rootMotion':False,'speedMetersPerSecond':2.5 if kind=='walk' else 5.7 if kind=='run' else 0}
rig.animation_data.action=None
reset_pose();scene.frame_set(1);bpy.context.view_layer.update()

rig['characterContract']='Meters; feet origin; export +Y up/+Z forward/+X left; animation drives pose only.'
rig['likeness']='Artist interpretation from user-provided photograph, with a requested Italian Coppola. No photo pixels embedded.'
rig['seatAnchorGame']=[.398,.1,-.315]
scene['asset']='Dad driver with Italian Coppola'

# Reusable studio remains in the .blend but is excluded from the game export.
studio=bpy.data.collections.new('REVIEW STUDIO | excluded from GLB');scene.collection.children.link(studio)
def studio_object(o):
    for c in list(o.users_collection):c.objects.unlink(o)
    studio.objects.link(o);return o
bpy.ops.mesh.primitive_plane_add(size=200,location=(0,0,-.014))
floor=studio_object(bpy.context.object);floor.name='Neutral studio floor';floor.data.materials.append(material('Studio floor',(.105,.125,.135),.85))
world=bpy.data.worlds.new('Soft studio environment');scene.world=world;world.use_nodes=True
world.node_tree.nodes['Background'].inputs[0].default_value=(.21,.24,.27,1);world.node_tree.nodes['Background'].inputs[1].default_value=.45
def area(name,position,power,size,color):
    data=bpy.data.lights.new(name,'AREA');data.energy=power;data.shape='DISK';data.size=size;data.color=color
    obj=bpy.data.objects.new(name,data);studio.objects.link(obj);obj.location=position;obj.rotation_euler=(Vector((0,0,1.0))-obj.location).to_track_quat('-Z','Y').to_euler()
area('Large portrait key',(-3,-4,5),650,4.0,(1,.88,.77))
area('Soft portrait fill',(3,-2,3),480,3.5,(.79,.88,1))
area('Shoulder and cap rim',(0,3,4),800,3,(1,.95,.88))
data=bpy.data.cameras.new('Review camera');camera=bpy.data.objects.new('Review camera',data);studio.objects.link(camera);scene.camera=camera
scene.render.engine='BLENDER_EEVEE';scene.render.resolution_percentage=100
scene.render.image_settings.file_format='PNG';scene.render.film_transparent=False
scene.view_settings.view_transform='AgX';scene.view_settings.look='AgX - Medium High Contrast'

bpy.ops.object.select_all(action='DESELECT');rig.select_set(True)
for obj in batched:obj.select_set(True)
bpy.context.view_layer.objects.active=rig
glb_path=ASSETS/'dad-driver.glb'
# glTF needs tangent-space normals. Blender's procedural Bump evaluation is not
# baked by the exporter: exporting that connection incorrectly reuses the color
# PNG as a normal map. Keep the studio's subtle bump in the editable .blend,
# but export only the valid cotton/tweed base colors and material roughness.
studio_normal_links=[]
for mat in (shirt,cap,tee):
    normal=mat.node_tree.nodes.get('Principled BSDF').inputs['Normal']
    for link in list(normal.links):
        studio_normal_links.append((mat.node_tree,link.from_socket,link.to_socket))
        mat.node_tree.links.remove(link)
try:
    bpy.ops.export_scene.gltf(filepath=str(glb_path),export_format='GLB',use_selection=True,export_yup=True,
                             export_animations=True,export_animation_mode='NLA_TRACKS',export_nla_strips=True,
                             export_force_sampling=True,export_skins=True,export_all_influences=False,
                             export_cameras=False,export_lights=False,export_extras=True,export_apply=False)
finally:
    for node_tree,source,target in studio_normal_links:node_tree.links.new(source,target)

raw=glb_path.read_bytes();json_length=struct.unpack_from('<I',raw,12)[0];gltf=json.loads(raw[20:20+json_length])
for mat in gltf.get('materials',[]):
    if mat.get('name') in (shirt.name,cap.name,tee.name):
        assert 'normalTexture' not in mat, 'Unbaked procedural height must never export as a tangent normal texture'
        assert 'baseColorTexture' in mat['pbrMetallicRoughness'], 'Original generated fabric must remain embedded'
# glTF's NLA sampler evaluates every clip and can leave Blender in the final
# pose. Explicitly restore the editable source and portrait to the bind pose.
rig.animation_data.action=None
for track in rig.animation_data.nla_tracks: track.mute=True
scene.frame_set(0);reset_pose();bpy.context.view_layer.update()
triangles=0
for obj in batched:obj.data.calc_loop_triangles();triangles+=len(obj.data.loop_triangles)
rest_vertices=[v.co for obj in batched for v in obj.data.vertices]
minimum=[min(v[i] for v in rest_vertices) for i in range(3)]
maximum=[max(v[i] for v in rest_vertices) for i in range(3)]
manifest={
 'version':1,'name':'Dad with Italian Coppola','asset':'/assets/dad-driver.glb','source':'asset-source/dad-driver.blend',
 'generator':'scripts/build-dad-driver.py','units':'meters','heightMeters':maximum[2]-minimum[2],
 'bounds':{'min':[minimum[0],minimum[2],-maximum[1]],'max':[maximum[0],maximum[2],-minimum[1]]},
 'axes':{'left':'+X','up':'+Y','forward':'+Z','sourceUp':'+Z','sourceForward':'-Y'},
 'origin':'feet','seatAnchorGame':[.398,.1,-.315],
 'rig':{'object':'DadDriverRig','bones':{name:{'headSource':h,'tailSource':t,'parent':parent} for name,(h,t,parent) in specs.items()},
        'conventions':'Blender bone local Y points head-to-tail; preserve exported bind rotation. All limb bend axes approximately local X; game transforms belong on an outer root.'},
 'animations':clips,'exportedClips':[a.get('name') for a in gltf.get('animations',[])],
 'statistics':{'triangles':triangles,'meshes':len(batched),'materials':len(gltf.get('materials',[])),'glbBytes':len(raw),'joints':len(specs)},
 'appearance':['rounded full face','prominent nose','silver white mustache without beard','thin rounded tinted wire glasses','salt and pepper side hair','low charcoal Italian Coppola','light blue checked open shirt','charcoal V-neck shirt','dark trousers and shoes'],
 'limits':['Stylized interpretation from one photograph; side/back proportions and hidden body details are inferred.','Hands have modeled fingers but no individual finger animation bones.','Procedural materials and mesh shapes are original; supplied photograph is not embedded.'],
}
(ASSETS/'dad-driver-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n',encoding='utf8')

def render(path, location, target, lens, width, height):
    camera.location=location;camera.rotation_euler=(Vector(target)-camera.location).to_track_quat('-Z','Y').to_euler();camera.data.lens=lens
    scene.render.resolution_x=width;scene.render.resolution_y=height;scene.render.filepath=str(path)
    bpy.ops.render.render(write_still=True)
render(DOCS/'dad-driver-blender-portrait.png',(.31,-1.5,1.76),(0,-.025,1.50),75,1200,1200)
render(DOCS/'dad-driver-blender-full-body.png',(1.8,-5.0,2.10),(0,0,.93),72,1000,1400)
# Review the exact baked wheel-reaching clip without changing the final source pose.
rig.animation_data.action=bpy.data.actions['Seated'];scene.frame_set(1);bpy.context.view_layer.update()
render(DOCS/'dad-driver-blender-seated.png',(2.6,-3.8,1.9),(0,-.15,.85),72,1100,1100)
rig.animation_data.action=None;scene.frame_set(0);reset_pose();bpy.context.view_layer.update()
camera.location=(.31,-1.5,1.76);camera.rotation_euler=(Vector((0,-.025,1.50))-camera.location).to_track_quat('-Z','Y').to_euler();camera.data.lens=75
bpy.ops.wm.save_as_mainfile(filepath=str(SOURCE/'dad-driver.blend'))
print('DAD_DRIVER_READY',json.dumps(manifest['statistics']),json.dumps(manifest['exportedClips']))
